
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_CONFIG=Release
  - BUILD_CONFIG=Debug

matrix:
  allow_failures:
    - compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-system-dev libboost-thread-dev libboost-test-dev libtinyxml-dev
install:

before_script:
  - mkdir build.ci
  - cd build.ci
  - cmake .. -DBUILD_UT=ON -DCMAKE_BUILD_TYPE=$BUILD_CONFIG -DUSE_STATIC_BOOST=YES 

script:
  - cmake --build .
  - ctest -VV
