sudo: false

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_CONFIG=Release
  - BUILD_CONFIG=Debug

matrix:
  allow_failures:
    - compiler: clang

before_install:

install:

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev
  - mkdir build.ci
  - cd build.ci
  - cmake .. -DBUILD_UT=ON -DCMAKE_BUILD_TYPE=$BUILD_CONFIG

script:
  - cmake --build .
  - ctest -VV
